### ISSUE TITLE
[enhance]mempool with tax detection and honeypot detection

### ISSUE THREAD

**Issue by kugimiya530** [tsarbuig/Limit-Sniper-V3#2]
i hope we can mempool snipe with sameblock tax and honeypot detection

and i know tax detection already implement thx alot

**Comment by tsarbuig** [comment]
the problem is the fact that : 
- to calculate BUY tax (what already exist), you need to create ONE buy tx before the real one --> your Tx fees will be 2x regular fees

- but to calculate if token is not a honeypot, you need to create TWO buy tx before the real one (one buy / one sell) --> your Tx fees will be THREE TIMES superior to regular fees

--> I think people are not aware of that and will be very, very surprised to have such high fees... so I think this is not a good idea

What do you think ?

**Comment by kugimiya530** [comment]
Hmm.. when we detection Tax we already buy a small test amount and sell
that to calculate the tax

Can we use that?

If can sell then not a honeypot

Don't know I am correct or not

TsarBuig ***@***.***> 於 2023年2月7日 週二 上午5:33 寫道：

**Comment by shootlazer** [comment]
> the problem is the fact that :
> 
> * to calculate BUY tax (what already exist), you need to create ONE buy tx before the real one --> your Tx fees will be 2x regular fees
> * but to calculate if token is not a honeypot, you need to create TWO buy tx before the real one (one buy / one sell) --> your Tx fees will be THREE TIMES superior to regular fees
> 
> --> I think people are not aware of that and will be very, very surprised to have such high fees... so I think this is not a good idea
> 
> What do you think ?

Just wondering... isn't it possible to fork the mainnet and run a simulation locally? If it is... that'd leave you space to do LOTS of things
